quality:
  final: "FIN"
  rapid: "RAP"
  real_time_streaming: "RTS"

regex:
  product_sp3: "{quality}.*{year}{doy}.*SP3.*"
  product_obx: "{quality}.*{year}{doy}.*OBX.*"
  product_clk: "{quality}.*{year}{doy}.*CLK.*"
  product_sum: "{quality}.*{year}{doy}.*SUM.*"
  product_bias: "{quality}.*{year}{doy}.*BIAS.*"
  product_erp: "{quality}.*{year}{doy}.*ERP.*"
  product_broadcast_rnx3: "BRDS.*{year}{doy}.*rnx.*"
  product_broadcast_rnx2: "brdc{doy}0.{yy}{constellation}.gz"


sources:
  wuhan:
    ftpserver: "ftp://igs.gnsswhu.cn"
    directories:
      rinex_nav: "pub/gps/data/daily/{year}/{doy}/{yy}p"
      product_sp3: "pub/whu/phasebias/{year}/orbit/"
      product_orbit: "pub/whu/phasebias/{year}/orbit/"
      product_clk: "pub/whu/phasebias/{year}/clock/"
      product_sum: "pub/whu/phasebias/{year}/clock/"
      product_bias: "pub/whu/phasebias/{year}/bias/"
      product_erp: "pub/whu/phasebias/{year}/orbit/"
      product_obx: "pub/whu/phasebias/{year}/orbit/"

  cligs:
    ftpserver: "ftp://igs.ign.fr"
    directories:
      rinex_nav: "pub/igs/data/{year}/{doy}"
      product_sp3: "pub/igs/data/{gps_week}/"
      product_clk: "pub/igs/data/{gps_week}/"
      product_erp: "pub/igs/data/{gps_week}/"
      product_obx: "pub/igs/data/{gps_week}/"
      product_bias: "pub/igs/data/{gps_week}/"





