test ={
    "id": "WUM",
    "name": "Wuhan University GNSS Research Center",
    "website": "http://www.igs.gnsswhu.cn/",
    "servers": [
        {
            "id": "wuhan_ftp",
            "name": "Primary FTP",
            "hostname": "ftp://igs.gnsswhu.cn",
            "protocol": "ftp",
            "auth_required": False,
            "notes": "Primary FTP server, no authentication required",
        }
    ],
    "products": [
        {
            "id": "wuhan_orbit",
            "product_name": "ORBIT",
            "server_id": "wuhan_ftp",
            "available": True,
            "description": "Precise satellite orbits",
            "parameters": [
                {"name": "YYYY"},
                {"name": "AAA", "value": "WUM"},
                {"name": "AAA","value":"WMC"},
                {"name":"TTT","value":"FIN"},
                {"name": "TTT", "value": "RAP"},
                {"name": "PPP", "value": "MGX"},
                {"name": "PPP", "value": "DEM"},
                {"name": "SMP", "value": "05M"},
                {"name": "SMP", "value": "15M"},
            ],
            "directory": {"pattern": "pub/whu/phasebias/{YYYY}/orbit/"},
        },
        {
            "id": "wuhan_clock",
            "product_name": "CLOCK",
            "server_id": "wuhan_ftp",
            "available": True,
            "description": "Precise satellite and station clocks",
            "parameters": [
                {"name": "YYYY"},
                {"name": "AAA", "value": "WUM"},
                {"name": "AAA", "value": "WMC"},
                {"name": "TTT", "value": "FIN"},
                {"name": "TTT", "value": "RAP"},
                {"name": "PPP", "value": "MGX"},
                {"name": "PPP", "value": "DEM"},
                {"name": "SMP", "value": "30S"},
                {"name": "SMP", "value": "05M"},
            ],
            "directory": {"pattern": "pub/whu/phasebias/{YYYY}/clock/"},
        },
    ],
}
